apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  annotations:
    # Optional for ALB ingress
spec:
  type: ClusterIP
  selector:
    app: springboot
  ports:
    - port: 80
      targetPort: 8080
