apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: default
spec:
  type: NodePort         # ALB will target pods by IP via NodePort service
  selector:
    app: springboot
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
