apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: kube-system  # only if your deployment is in kube-system; adjust accordingly
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
spec:
  type: LoadBalancer
  selector:
    app: springboot
  ports:
    - port: 80
      targetPort: 8080
